[FIX] Exclude recent l10n_fr certification modules This should fix tests as all localization modules are excluded, but the OCA travis script will prepare a test database that includes any modules that are excluded but are dependencies of modules that are not excluded. In this case, l10n_fr is installed in this pre-stage, which depends on the account module and friends. But not all modules support reloading of demo data.
loading l10n_generic_coa/../account/demo/account_invoice_demo.yml
2017-12-22 13:49:37,362 5185 ERROR openerp_test odoo.sql_db: bad query: b'INSERT INTO "account_invoice_line" ("id", "account_id", "quantity", "product_id", "discount", "is_rounding_line", "sequence", "invoice_id", "price_unit", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval(\'account_invoice_line_id_seq\'), NULL, \'5.000\', 36, \'0.00\', false, 10, 1, \'642.00\', 1, 1, (now() at time zone \'UTC\'), (now() at time zone \'UTC\')) RETURNING id'
ERROR: null value in column "name" violates not-null constraint